# Project-1---> Iris Flower Classification

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('iris.csv')

In [3]:
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [4]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
x=df.iloc[:,0:4].values

In [6]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y=df.iloc[:,4].values

In [8]:
y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Logistic regression algorithm

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
y_pred = logmodel.predict(x_test)
y_pred

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 1, 1, 2, 0, 2, 1, 1])

In [17]:
y_test

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1])

In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  7]])

## Accuracy

In [20]:
29/30

0.9666666666666667

# KNN algorithm

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
classifier_Knn = KNeighborsClassifier(n_neighbors=5)
classifier_Knn.fit(x_train,y_train)

KNeighborsClassifier()

In [23]:
y_pred=classifier_Knn.predict(x_test)

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [24]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  7]])

## Accuracy

In [25]:
30/30

1.0

# Naive bayes classifier algorithm

In [26]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [27]:
y_pred = classifier_nb.predict(x_test)

In [28]:
y_pred

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 1, 1, 2, 0, 1, 1, 1])

In [29]:
y_test

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1])

In [30]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  6]])

## Accuracy

In [31]:
29/30

0.9666666666666667

# Support Vector Machine (sigmoid)

In [32]:
from sklearn.svm import SVC

In [33]:
classifier_svm_sigmoid = SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [34]:
y_pred = classifier_svm_sigmoid.predict(x_test)

In [35]:
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [36]:
y_test

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1])

In [37]:
confusion_matrix(y_test,y_pred)

array([[ 0,  0, 12],
       [ 0,  0, 10],
       [ 0,  0,  8]])

## Accuracy

In [38]:
9/30

0.3

# Support Vector Machine (linear)

In [39]:
from sklearn.svm import SVC

In [40]:
classifier_svm_linear = SVC(kernel='linear')
classifier_svm_linear.fit(x_train,y_train)

SVC(kernel='linear')

In [41]:
y_pred = classifier_svm_linear.predict(x_test)

In [42]:
y_pred

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1])

In [43]:
y_test

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1])

In [44]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  8]])

## Accuracy

In [45]:
29/30

0.9666666666666667

# Support Vector Machine (rbf)

In [46]:
from sklearn.svm import SVC

In [47]:
classifier_svm_rbf = SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train,y_train)

SVC()

In [48]:
y_pred = classifier_svm_rbf.predict(x_test)

In [49]:
y_pred

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 1, 1, 2, 0, 2, 1, 1])

In [50]:
y_test

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1])

In [51]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  7]])

## Accuracy

In [52]:
30/30

1.0

# Support Vector Machine (poly)

In [53]:
from sklearn.svm import SVC
classifier_svm_poly = SVC(kernel='poly')
classifier_svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [54]:
y_pred = classifier_svm_poly.predict(x_test)

In [55]:
y_pred

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1])

In [56]:
y_test

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1])

In [57]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  8]])

## Accuracy

In [58]:
28/30

0.9333333333333333

# Decision Tree

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
classifier_dt = DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [61]:
y_pred = classifier_dt.predict(x_test)

In [62]:
y_pred

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 1, 1, 2, 0, 1, 1, 1])

In [63]:
y_test

array([1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1])

In [64]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  6]])

## Accuracy

In [65]:
29/30

0.9666666666666667

# Random Forest

In [66]:
from sklearn.ensemble import RandomForestClassifier

In [67]:
classifier_rf = RandomForestClassifier(n_estimators=3,criterion='entropy')
classifier_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [68]:
y_pred = classifier_rf.predict(x_test)

In [69]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  3,  5]])

## Accuracy

In [70]:
29/30

0.9666666666666667